import tkinter as tk
from tkinter.font import BOLD
import tkinter.ttk as ttk
import spotipy
import random
from tkinter import messagebox
from spotipy.oauth2 import SpotifyOAuth

scope = " playlist-modify-public playlist-read-private"
my_username = "l6pii8uua3baeavix82fbffl7"
token = SpotifyOAuth(
    scope=scope,
    username=my_username,
    client_id="""CLIENT_ID""",
    client_secret="""CLIENT_ID_SECRET""",
    redirect_uri="http://127.0.0.1:8080",
)
spotify = spotipy.Spotify(auth_manager=token)


def create_playlist(name, desc):
    """Give the Name of the playlist and a short description."""
    spotify.user_playlist_create(
        user=my_username, public=True, description=desc, name=name
    )


def get_playlist(n):
    """returns a list if entered 1 and also returns a dictionary if 0 is entered"""
    d_nory = {}
    ls = []
    data = spotify.current_user_playlists()
    for i in data["items"]:
        d_nory[i["name"]] = i["id"]
    for i in d_nory:
        ls.append(i)
    if n == 0:
        return ls, d_nory
    elif n == 1:
        return d_nory


def enable_menu(e):
    shf_btn.config(state=tk.ACTIVE)


play_list, play_dict = get_playlist(0)


root = tk.Tk()
root.title("Shufflify")
root.config(bg="#222224")
root.geometry("800x150")


def shuffle():
    def get_id(pl_nme):
        print(play_dict[pl_nme])

    p_name = str(playlist_menu.get()) + " (Shuffled)"
    p_desc = "This is a shuffled playlist generated by VarunAdhityaGB. Do give a follow: https://twitter.com/Varunadhitya31"
    p_id = play_dict[playlist_menu.get()]

    song_ls = []
    song_c = countvar.get()
    for i in range(0, song_c, 100):
        song_d = (spotify.playlist_tracks(playlist_id=p_id, offset=i))["items"]
        for i in song_d:
            song_ls.append(i["track"]["uri"])
    random.shuffle(song_ls)

    create_playlist(p_name, p_desc)
    d2_nory = get_playlist(1)
    messagebox.showinfo(
        "Shufflify",
        "Playlist successfully shuffled.\n Click OK then Check your library AFTER THE MAIN WINDOW CLOSES.",
    )
    for i in song_ls:
        spotify.playlist_add_items(
            playlist_id=str(d2_nory[p_name]), items=[i], position=None
        )
    root.destroy()


main_frm = tk.Frame(root, bg="#222224")
main_frm.pack(anchor=tk.CENTER)
countvar = tk.IntVar()
playlist_menu = ttk.Combobox(
    main_frm, values=play_list, font=("", 14), background="#222224", width=50
)
playlist_lbl = tk.Label(
    main_frm,
    text="Playlists",
    font=("", 15, BOLD),
    background="#222224",
    foreground="white",
)
song_c_lbl = tk.Label(
    main_frm,
    text="Number of songs: ",
    font=("", 15, BOLD),
    background="#222224",
    foreground="white",
)
song_c_ent = tk.Entry(main_frm, textvariable=countvar, font=("", 14))
shf_btn = ttk.Button(main_frm, text="Shuffle", command=shuffle, state=tk.DISABLED)

playlist_lbl.grid(row=0, column=0, padx=10, pady=10)
playlist_menu.grid(row=0, column=1, padx=10, pady=10)
song_c_lbl.grid(row=1, column=0, padx=10, pady=10)
song_c_ent.grid(row=1, column=1, padx=10, pady=10)
shf_btn.grid(row=2, column=0, columnspan=2, pady=25)

playlist_menu.bind("<Button-1>", enable_menu)

root.mainloop()
